### ISSUE TITLE
Can't create button on Fusion 360 when we imported yaml

### ISSUE THREAD

**Issue by ach238** [AguaClara/aide_gui#11]
@ethan92429 We created a function that will parse a yaml and dynamically create global variables based on the parameter names (pushed to GitHub), but for some reason when we insert the line `import yaml`, nothing shows up on the Fusion 360 interface (no buttons under the create module), where there used to be an aide_gui button when we used JSONs. Any solutions?

**Comment by ach238** [comment]
We're also having issues opening the JSON file if you could take a look at our code. We found your post on the Fusion forums so hopefully you have it figured out https://forums.autodesk.com/t5/fusion-360-api-and-scripts/open-file-using-relative-paths/td-p/7535575

**Comment by ethan92429** [comment]
I just looked at your code, and it is very confusing, I think this is because you copied some boilerplate gear code. Please delete as much of that as possible. The total solution to the project I posted should be no more than 100 lines of code. The reason yaml isn't working is because Python can't find the pyyaml package on your machine. Python needs to have this package available on it's path so that it can import it. So you need to find out where the pyyaml binary exists, and then add it to your path. See here for an example. [This](https://github.com/AguaClara/aide_draw/blob/93547de5b8620e1a3f1c2d47d5cc44d75460467e/aide.py#L22) is how I solved the problem, but as I said in the comments, it's very dirty. You have to find your own local site_packages location and put it in. This is still something I need to figure out how to do elegantly. Lastly, to open a file with a relative path, see [this code. ](https://github.com/AguaClara/aide_draw/blob/93547de5b8620e1a3f1c2d47d5cc44d75460467e/utilities.py#L8)

**Comment by ach238** [comment]
We've been working on open_json.py and open_yaml.py but we'll take a look at what you linked and clean things up, thanks!
